### PR TITLE
Add AWS region, username, app ID and subdomain as optional command-line arguments

### PR DESCRIPTION
**Pull request by kepten**
For better UX, make it possible to provide static parameters via command-line argument and ask for dynamic inputs only (like passwords, MFA code).
If something is not passed as argument, let default to the old behaviour: ask for it interactively.

### CODE REVIEW

**Comment by pitbulk** [comment]
In order to keep compatibility, what do you think to accept onelogin username, password and region by args, but keep also the old behavior. We have customers that use it that way.

**Comment by kepten** [comment]
@pitbulk I updated the PR description to make it clear why it is a backward-compatible change. Do you think it is not?

**Comment by pitbulk** [comment]
ohh sorry, I thought you made a replacement... but you made exactly what I expected ;)

**Comment by kepten** [comment]
No worries, I updated the `README` as well.

**Comment by korsosa** [comment]
🎉

**Pull request merged**
