### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by kylecrawshaw**
This change makes `aws_assume_role` it's own python package instead of trying to inject itself into the `onelogin` installed package. I've updated symlinks to ensure backwards compatibility with previous execution methods. See my comments in #20

### CODE REVIEW

**Comment by pitbulk** [comment]
I followed those steps:
```
git clone https://github.com/kylecrawshaw/onelogin-python-aws-assume-role.git
cd onelogin-python-aws-assume-role
virtualenv venv
source venv/activate
python setup.py install
onelogin-aws-assume-role
```
and got
```
onelogin-aws-assume-role: order not found
```

**Comment by kylecrawshaw** [comment]
@pitbulk I'm unable to reproduce that issue. Are you on macOS, Windows or Linux? Curious the `entry_point` has different behavior on different os's

**Comment by pitbulk** [comment]
I'm using Ubuntu. Have you reproduce the steps without issues?

**Comment by kylecrawshaw** [comment]
Yes, I run those exact commands in a fresh environment running python 2.7.10 and it works without issue.

**Comment by pitbulk** [comment]
No onelogin-aws-assume-role binary
```
ls venv/bin/
activate       activate_this.py  easy_install-2.7  pip2    python2        rst2html4.py  rst2latex.py           rst2odt.py        rst2xetex.py    wheel
activate.csh   chardetect        jp.py             pip2.7  python2.7      rst2html5.py  rst2man.py             rst2pseudoxml.py  rst2xml.py
activate.fish  easy_install      pip               python  python-config  rst2html.py   rst2odt_prepstyles.py  rst2s5.py         rstpep2html.py
```

**Comment by kylecrawshaw** [comment]
Weird. I'll install in an Ubuntu Docker container since that is the closest I can get to an Ubuntu OS for now.

**Comment by pitbulk** [comment]
Forget that, I was testing with your master branch...

**Comment by kylecrawshaw** [comment]
Ahhh ok I almost asked. Excellent. Thanks for merging.

**Pull request merged**
